import { Check } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Reveal } from "./reveal";
const free = ["Visual workflow builder", "Credential management", "Execution history", "Core integrations"];
const pro = ["Higher automation limits", "More room for production workflows", "Polar-powered subscription management", "Everything in Free"];
export function Pricing() { return <section id="pricing" className="mx-auto max-w-6xl px-4 py-24 sm:px-6"><Reveal><span className="font-mono text-xs uppercase tracking-wide text-primary">Pricing</span><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Start building before you upgrade.</h2><p className="mt-3 max-w-xl text-muted-foreground">Use the free tier to build and test workflows. Pro is available when you need higher limits.</p></Reveal><div className="mt-10 grid gap-6 md:grid-cols-2"><PriceCard title="Free" features={free} cta="Start free" /><PriceCard title="Pro" features={pro} cta="Get Pro" featured /></div></section>; }
function PriceCard({ title, features, cta, featured = false }: { title: string; features: string[]; cta: string; featured?: boolean }) { return <Reveal><Card className={featured ? "h-full border-primary/30 bg-primary/5 ring-1 ring-primary/20" : "h-full"}><CardHeader><span className={featured ? "text-sm font-medium text-primary" : "text-sm font-medium text-muted-foreground"}>{title}</span><p className="text-2xl font-semibold">{title === "Free" ? "Free forever to start" : "Upgrade in-app"}</p></CardHeader><CardContent><ul className="space-y-3">{features.map(x => <li key={x} className="flex gap-2 text-sm text-muted-foreground"><Check className="mt-0.5 size-4 shrink-0 text-primary" />{x}</li>)}</ul><Button className="mt-7 w-full" variant={featured ? "default" : "outline"} asChild><Link href="/signup">{cta}</Link></Button></CardContent></Card></Reveal>; }
