export const CHANNELS = {
  MANUAL_TRIGGER: "manualTriggerExec",
  GOOGLE_FORM_TRIGGER: "googleFormTriggerExec",
  STRIPE_TRIGGER: "stripeTriggerExec",
  WEBHOOK_TRIGGER: "webhookTriggerExec",
  TELEGRAM_TRIGGER: "telegramTriggerExec",
  HTTP_TRIGGER: "httpTriggerExec",
  SET: "setExec",
  GEMINI: "geminiExec",
  BLACK_FOREST: "blackForestExec",
  OPENAI: "openaiExec",
  ANTHROPIC: "anthropicExec",
  DISCORD: "discordExec",
  SLACK: "slackExec",
} as const;
